name: Lint and Test with Coverage

on:
  push:
    branches:
      - main
      - CR1
      - CR2
      - CR3
  pull_request:

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Install and configure Xvfb for headless GUI tests
      - name: Install Xvfb
        run: sudo apt-get install -y xvfb

      - name: Start Xvfb
        run: |
          export DISPLAY=:99
          Xvfb :99 -screen 0 1024x768x16 > /dev/null 2>&1 &

      # Run linting
      - name: Run flake8
        run: flake8 --exclude input/projects/example,test/system_testing,datasets .


      # Run tests with pytest and collect coverage
      - name: Run tests and collect coverage
        run: |
          coverage run --branch -m pytest --ignore=datasets --ignore=webapp/integration_tests --ignore=finetuning
          coverage report -m
          coverage xml


      # Upload coverage report to Codecov
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          fail_ci_if_error: true
